
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "encerrarApontamentoEquipamentoService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/encerrarApontamentoEquipamentoServiceDefinition.wsdl")
public class EncerrarApontamentoEquipamentoService
    extends Service
{

    private final static URL ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_EXCEPTION;
    private final static QName ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "encerrarApontamentoEquipamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/encerrarApontamentoEquipamentoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_WSDL_LOCATION = url;
        ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_EXCEPTION = e;
    }

    public EncerrarApontamentoEquipamentoService() {
        super(__getWsdlLocation(), ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_QNAME);
    }

    public EncerrarApontamentoEquipamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public EncerrarApontamentoEquipamentoService(URL wsdlLocation) {
        super(wsdlLocation, ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_QNAME);
    }

    public EncerrarApontamentoEquipamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public EncerrarApontamentoEquipamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncerrarApontamentoEquipamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EncerrarApontamentoEquipamento
     */
    @WebEndpoint(name = "encerrarApontamentoEquipamentoSoap11")
    public EncerrarApontamentoEquipamento getEncerrarApontamentoEquipamentoSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "encerrarApontamentoEquipamentoSoap11"), EncerrarApontamentoEquipamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EncerrarApontamentoEquipamento
     */
    @WebEndpoint(name = "encerrarApontamentoEquipamentoSoap11")
    public EncerrarApontamentoEquipamento getEncerrarApontamentoEquipamentoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "encerrarApontamentoEquipamentoSoap11"), EncerrarApontamentoEquipamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_EXCEPTION!= null) {
            throw ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_EXCEPTION;
        }
        return ENCERRARAPONTAMENTOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    }

}
