
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirApontamentoProducaoService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirApontamentoProducaoServiceDefinition.wsdl")
public class ExcluirApontamentoProducaoService
    extends Service
{

    private final static URL EXCLUIRAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIRAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
    private final static QName EXCLUIRAPONTAMENTOPRODUCAOSERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoProducaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirApontamentoProducaoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIRAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION = url;
        EXCLUIRAPONTAMENTOPRODUCAOSERVICE_EXCEPTION = e;
    }

    public ExcluirApontamentoProducaoService() {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public ExcluirApontamentoProducaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public ExcluirApontamentoProducaoService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public ExcluirApontamentoProducaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public ExcluirApontamentoProducaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirApontamentoProducaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirApontamentoProducao
     */
    @WebEndpoint(name = "excluirApontamentoProducaoSoap11")
    public ExcluirApontamentoProducao getExcluirApontamentoProducaoSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoProducaoSoap11"), ExcluirApontamentoProducao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirApontamentoProducao
     */
    @WebEndpoint(name = "excluirApontamentoProducaoSoap11")
    public ExcluirApontamentoProducao getExcluirApontamentoProducaoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoProducaoSoap11"), ExcluirApontamentoProducao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIRAPONTAMENTOPRODUCAOSERVICE_EXCEPTION!= null) {
            throw EXCLUIRAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
        }
        return EXCLUIRAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    }

}
