
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirApontamentoQuantidadeService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirApontamentoQuantidadeServiceDefinition.wsdl")
public class ExcluirApontamentoQuantidadeService
    extends Service
{

    private final static URL EXCLUIRAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIRAPONTAMENTOQUANTIDADESERVICE_EXCEPTION;
    private final static QName EXCLUIRAPONTAMENTOQUANTIDADESERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoQuantidadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirApontamentoQuantidadeServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIRAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION = url;
        EXCLUIRAPONTAMENTOQUANTIDADESERVICE_EXCEPTION = e;
    }

    public ExcluirApontamentoQuantidadeService() {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOQUANTIDADESERVICE_QNAME);
    }

    public ExcluirApontamentoQuantidadeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOQUANTIDADESERVICE_QNAME, features);
    }

    public ExcluirApontamentoQuantidadeService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOQUANTIDADESERVICE_QNAME);
    }

    public ExcluirApontamentoQuantidadeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOQUANTIDADESERVICE_QNAME, features);
    }

    public ExcluirApontamentoQuantidadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirApontamentoQuantidadeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirApontamentoQuantidade
     */
    @WebEndpoint(name = "excluirApontamentoQuantidadeSoap11")
    public ExcluirApontamentoQuantidade getExcluirApontamentoQuantidadeSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoQuantidadeSoap11"), ExcluirApontamentoQuantidade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirApontamentoQuantidade
     */
    @WebEndpoint(name = "excluirApontamentoQuantidadeSoap11")
    public ExcluirApontamentoQuantidade getExcluirApontamentoQuantidadeSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoQuantidadeSoap11"), ExcluirApontamentoQuantidade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIRAPONTAMENTOQUANTIDADESERVICE_EXCEPTION!= null) {
            throw EXCLUIRAPONTAMENTOQUANTIDADESERVICE_EXCEPTION;
        }
        return EXCLUIRAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION;
    }

}
