
package br.feevale.tc.oee.ws.apontamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "excluirApontamentoProducao", targetNamespace = "apontamento.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExcluirApontamentoProducao {


    /**
     * 
     * @param excluirApontamentoProducaoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.apontamento.ExcluirApontamentoProducaoResponse
     */
    @WebMethod
    @WebResult(name = "excluirApontamentoProducaoResponse", targetNamespace = "apontamento.ws.oee.tc.feevale.br", partName = "excluirApontamentoProducaoResponse")
    public ExcluirApontamentoProducaoResponse excluirApontamentoProducao(
        @WebParam(name = "excluirApontamentoProducaoRequest", targetNamespace = "apontamento.ws.oee.tc.feevale.br", partName = "excluirApontamentoProducaoRequest")
        ExcluirApontamentoProducaoRequest excluirApontamentoProducaoRequest);

}
