
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirApontamentoParadaService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirApontamentoParadaServiceDefinition.wsdl")
public class ExcluirApontamentoParadaService
    extends Service
{

    private final static URL EXCLUIRAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIRAPONTAMENTOPARADASERVICE_EXCEPTION;
    private final static QName EXCLUIRAPONTAMENTOPARADASERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoParadaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirApontamentoParadaServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIRAPONTAMENTOPARADASERVICE_WSDL_LOCATION = url;
        EXCLUIRAPONTAMENTOPARADASERVICE_EXCEPTION = e;
    }

    public ExcluirApontamentoParadaService() {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOPARADASERVICE_QNAME);
    }

    public ExcluirApontamentoParadaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIRAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public ExcluirApontamentoParadaService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOPARADASERVICE_QNAME);
    }

    public ExcluirApontamentoParadaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIRAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public ExcluirApontamentoParadaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirApontamentoParadaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirApontamentoParada
     */
    @WebEndpoint(name = "excluirApontamentoParadaSoap11")
    public ExcluirApontamentoParada getExcluirApontamentoParadaSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoParadaSoap11"), ExcluirApontamentoParada.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirApontamentoParada
     */
    @WebEndpoint(name = "excluirApontamentoParadaSoap11")
    public ExcluirApontamentoParada getExcluirApontamentoParadaSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "excluirApontamentoParadaSoap11"), ExcluirApontamentoParada.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIRAPONTAMENTOPARADASERVICE_EXCEPTION!= null) {
            throw EXCLUIRAPONTAMENTOPARADASERVICE_EXCEPTION;
        }
        return EXCLUIRAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    }

}
