
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "iniciarApontamentoParadaService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/iniciarApontamentoParadaServiceDefinition.wsdl")
public class IniciarApontamentoParadaService
    extends Service
{

    private final static URL INICIARAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    private final static WebServiceException INICIARAPONTAMENTOPARADASERVICE_EXCEPTION;
    private final static QName INICIARAPONTAMENTOPARADASERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoParadaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/iniciarApontamentoParadaServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INICIARAPONTAMENTOPARADASERVICE_WSDL_LOCATION = url;
        INICIARAPONTAMENTOPARADASERVICE_EXCEPTION = e;
    }

    public IniciarApontamentoParadaService() {
        super(__getWsdlLocation(), INICIARAPONTAMENTOPARADASERVICE_QNAME);
    }

    public IniciarApontamentoParadaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INICIARAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public IniciarApontamentoParadaService(URL wsdlLocation) {
        super(wsdlLocation, INICIARAPONTAMENTOPARADASERVICE_QNAME);
    }

    public IniciarApontamentoParadaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INICIARAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public IniciarApontamentoParadaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IniciarApontamentoParadaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IniciarApontamentoParada
     */
    @WebEndpoint(name = "iniciarApontamentoParadaSoap11")
    public IniciarApontamentoParada getIniciarApontamentoParadaSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoParadaSoap11"), IniciarApontamentoParada.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IniciarApontamentoParada
     */
    @WebEndpoint(name = "iniciarApontamentoParadaSoap11")
    public IniciarApontamentoParada getIniciarApontamentoParadaSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoParadaSoap11"), IniciarApontamentoParada.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INICIARAPONTAMENTOPARADASERVICE_EXCEPTION!= null) {
            throw INICIARAPONTAMENTOPARADASERVICE_EXCEPTION;
        }
        return INICIARAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    }

}
