
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "iniciarApontamentoProducaoService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/iniciarApontamentoProducaoServiceDefinition.wsdl")
public class IniciarApontamentoProducaoService
    extends Service
{

    private final static URL INICIARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INICIARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
    private final static QName INICIARAPONTAMENTOPRODUCAOSERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoProducaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/iniciarApontamentoProducaoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INICIARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION = url;
        INICIARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION = e;
    }

    public IniciarApontamentoProducaoService() {
        super(__getWsdlLocation(), INICIARAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public IniciarApontamentoProducaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INICIARAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public IniciarApontamentoProducaoService(URL wsdlLocation) {
        super(wsdlLocation, INICIARAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public IniciarApontamentoProducaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INICIARAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public IniciarApontamentoProducaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IniciarApontamentoProducaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IniciarApontamentoProducao
     */
    @WebEndpoint(name = "iniciarApontamentoProducaoSoap11")
    public IniciarApontamentoProducao getIniciarApontamentoProducaoSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoProducaoSoap11"), IniciarApontamentoProducao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IniciarApontamentoProducao
     */
    @WebEndpoint(name = "iniciarApontamentoProducaoSoap11")
    public IniciarApontamentoProducao getIniciarApontamentoProducaoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "iniciarApontamentoProducaoSoap11"), IniciarApontamentoProducao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INICIARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION!= null) {
            throw INICIARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
        }
        return INICIARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    }

}
