
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirOuAlterarApontamentoParadaService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirOuAlterarApontamentoParadaServiceDefinition.wsdl")
public class InserirOuAlterarApontamentoParadaService
    extends Service
{

    private final static URL INSERIROUALTERARAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIROUALTERARAPONTAMENTOPARADASERVICE_EXCEPTION;
    private final static QName INSERIROUALTERARAPONTAMENTOPARADASERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoParadaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirOuAlterarApontamentoParadaServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIROUALTERARAPONTAMENTOPARADASERVICE_WSDL_LOCATION = url;
        INSERIROUALTERARAPONTAMENTOPARADASERVICE_EXCEPTION = e;
    }

    public InserirOuAlterarApontamentoParadaService() {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOPARADASERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoParadaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoParadaService(URL wsdlLocation) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOPARADASERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoParadaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOPARADASERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoParadaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirOuAlterarApontamentoParadaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirOuAlterarApontamentoParada
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoParadaSoap11")
    public InserirOuAlterarApontamentoParada getInserirOuAlterarApontamentoParadaSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoParadaSoap11"), InserirOuAlterarApontamentoParada.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirOuAlterarApontamentoParada
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoParadaSoap11")
    public InserirOuAlterarApontamentoParada getInserirOuAlterarApontamentoParadaSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoParadaSoap11"), InserirOuAlterarApontamentoParada.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIROUALTERARAPONTAMENTOPARADASERVICE_EXCEPTION!= null) {
            throw INSERIROUALTERARAPONTAMENTOPARADASERVICE_EXCEPTION;
        }
        return INSERIROUALTERARAPONTAMENTOPARADASERVICE_WSDL_LOCATION;
    }

}
