
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirOuAlterarApontamentoQuantidadeService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirOuAlterarApontamentoQuantidadeServiceDefinition.wsdl")
public class InserirOuAlterarApontamentoQuantidadeService
    extends Service
{

    private final static URL INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_EXCEPTION;
    private final static QName INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoQuantidadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirOuAlterarApontamentoQuantidadeServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION = url;
        INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_EXCEPTION = e;
    }

    public InserirOuAlterarApontamentoQuantidadeService() {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoQuantidadeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoQuantidadeService(URL wsdlLocation) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoQuantidadeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoQuantidadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirOuAlterarApontamentoQuantidadeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirOuAlterarApontamentoQuantidade
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoQuantidadeSoap11")
    public InserirOuAlterarApontamentoQuantidade getInserirOuAlterarApontamentoQuantidadeSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoQuantidadeSoap11"), InserirOuAlterarApontamentoQuantidade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirOuAlterarApontamentoQuantidade
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoQuantidadeSoap11")
    public InserirOuAlterarApontamentoQuantidade getInserirOuAlterarApontamentoQuantidadeSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoQuantidadeSoap11"), InserirOuAlterarApontamentoQuantidade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_EXCEPTION!= null) {
            throw INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_EXCEPTION;
        }
        return INSERIROUALTERARAPONTAMENTOQUANTIDADESERVICE_WSDL_LOCATION;
    }

}
