
package br.feevale.tc.oee.ws.apontamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirOuAlterarApontamentoProducaoService", targetNamespace = "apontamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirOuAlterarApontamentoProducaoServiceDefinition.wsdl")
public class InserirOuAlterarApontamentoProducaoService
    extends Service
{

    private final static URL INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
    private final static QName INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoProducaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirOuAlterarApontamentoProducaoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION = url;
        INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION = e;
    }

    public InserirOuAlterarApontamentoProducaoService() {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoProducaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoProducaoService(URL wsdlLocation) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_QNAME);
    }

    public InserirOuAlterarApontamentoProducaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_QNAME, features);
    }

    public InserirOuAlterarApontamentoProducaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirOuAlterarApontamentoProducaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirOuAlterarApontamentoProducao
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoProducaoSoap11")
    public InserirOuAlterarApontamentoProducao getInserirOuAlterarApontamentoProducaoSoap11() {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoProducaoSoap11"), InserirOuAlterarApontamentoProducao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirOuAlterarApontamentoProducao
     */
    @WebEndpoint(name = "inserirOuAlterarApontamentoProducaoSoap11")
    public InserirOuAlterarApontamentoProducao getInserirOuAlterarApontamentoProducaoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("apontamento.ws.oee.tc.feevale.br", "inserirOuAlterarApontamentoProducaoSoap11"), InserirOuAlterarApontamentoProducao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION!= null) {
            throw INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_EXCEPTION;
        }
        return INSERIROUALTERARAPONTAMENTOPRODUCAOSERVICE_WSDL_LOCATION;
    }

}
