
package br.feevale.tc.oee.ws.programacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "excluirProgramacaoProducaoEquipamento", targetNamespace = "programacao.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExcluirProgramacaoProducaoEquipamento {


    /**
     * 
     * @param excluirProgramacaoProducaoEquipamentoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.programacao.ExcluirProgramacaoProducaoEquipamentoResponse
     */
    @WebMethod
    @WebResult(name = "excluirProgramacaoProducaoEquipamentoResponse", targetNamespace = "programacao.ws.oee.tc.feevale.br", partName = "excluirProgramacaoProducaoEquipamentoResponse")
    public ExcluirProgramacaoProducaoEquipamentoResponse excluirProgramacaoProducaoEquipamento(
        @WebParam(name = "excluirProgramacaoProducaoEquipamentoRequest", targetNamespace = "programacao.ws.oee.tc.feevale.br", partName = "excluirProgramacaoProducaoEquipamentoRequest")
        ExcluirProgramacaoProducaoEquipamentoRequest excluirProgramacaoProducaoEquipamentoRequest);

}
