
package br.feevale.tc.oee.ws.programacao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirOuAlterarProgramacaoProducaoEquipamentoService", targetNamespace = "programacao.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirOuAlterarProgramacaoProducaoEquipamentoServiceDefinition.wsdl")
public class InserirOuAlterarProgramacaoProducaoEquipamentoService
    extends Service
{

    private final static URL INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION;
    private final static QName INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME = new QName("programacao.ws.oee.tc.feevale.br", "inserirOuAlterarProgramacaoProducaoEquipamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirOuAlterarProgramacaoProducaoEquipamentoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION = url;
        INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION = e;
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService() {
        super(__getWsdlLocation(), INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME);
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService(URL wsdlLocation) {
        super(wsdlLocation, INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME);
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirOuAlterarProgramacaoProducaoEquipamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirOuAlterarProgramacaoProducaoEquipamento
     */
    @WebEndpoint(name = "inserirOuAlterarProgramacaoProducaoEquipamentoSoap11")
    public InserirOuAlterarProgramacaoProducaoEquipamento getInserirOuAlterarProgramacaoProducaoEquipamentoSoap11() {
        return super.getPort(new QName("programacao.ws.oee.tc.feevale.br", "inserirOuAlterarProgramacaoProducaoEquipamentoSoap11"), InserirOuAlterarProgramacaoProducaoEquipamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirOuAlterarProgramacaoProducaoEquipamento
     */
    @WebEndpoint(name = "inserirOuAlterarProgramacaoProducaoEquipamentoSoap11")
    public InserirOuAlterarProgramacaoProducaoEquipamento getInserirOuAlterarProgramacaoProducaoEquipamentoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("programacao.ws.oee.tc.feevale.br", "inserirOuAlterarProgramacaoProducaoEquipamentoSoap11"), InserirOuAlterarProgramacaoProducaoEquipamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION!= null) {
            throw INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_EXCEPTION;
        }
        return INSERIROUALTERARPROGRAMACAOPRODUCAOEQUIPAMENTOSERVICE_WSDL_LOCATION;
    }

}
