
package br.feevale.tc.oee.ws.motivoparada;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirMotivoParadaService", targetNamespace = "motivoParada.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirMotivoParadaServiceDefinition.wsdl")
public class ExcluirMotivoParadaService
    extends Service
{

    private final static URL EXCLUIRMOTIVOPARADASERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIRMOTIVOPARADASERVICE_EXCEPTION;
    private final static QName EXCLUIRMOTIVOPARADASERVICE_QNAME = new QName("motivoParada.ws.oee.tc.feevale.br", "excluirMotivoParadaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirMotivoParadaServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIRMOTIVOPARADASERVICE_WSDL_LOCATION = url;
        EXCLUIRMOTIVOPARADASERVICE_EXCEPTION = e;
    }

    public ExcluirMotivoParadaService() {
        super(__getWsdlLocation(), EXCLUIRMOTIVOPARADASERVICE_QNAME);
    }

    public ExcluirMotivoParadaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIRMOTIVOPARADASERVICE_QNAME, features);
    }

    public ExcluirMotivoParadaService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIRMOTIVOPARADASERVICE_QNAME);
    }

    public ExcluirMotivoParadaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIRMOTIVOPARADASERVICE_QNAME, features);
    }

    public ExcluirMotivoParadaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirMotivoParadaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirMotivoParada
     */
    @WebEndpoint(name = "excluirMotivoParadaSoap11")
    public ExcluirMotivoParada getExcluirMotivoParadaSoap11() {
        return super.getPort(new QName("motivoParada.ws.oee.tc.feevale.br", "excluirMotivoParadaSoap11"), ExcluirMotivoParada.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirMotivoParada
     */
    @WebEndpoint(name = "excluirMotivoParadaSoap11")
    public ExcluirMotivoParada getExcluirMotivoParadaSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("motivoParada.ws.oee.tc.feevale.br", "excluirMotivoParadaSoap11"), ExcluirMotivoParada.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIRMOTIVOPARADASERVICE_EXCEPTION!= null) {
            throw EXCLUIRMOTIVOPARADASERVICE_EXCEPTION;
        }
        return EXCLUIRMOTIVOPARADASERVICE_WSDL_LOCATION;
    }

}
