
package br.feevale.tc.oee.ws.equipamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirEquipamentoService", targetNamespace = "equipamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirEquipamentoServiceDefinition.wsdl")
public class ExcluirEquipamentoService
    extends Service
{

    private final static URL EXCLUIREQUIPAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIREQUIPAMENTOSERVICE_EXCEPTION;
    private final static QName EXCLUIREQUIPAMENTOSERVICE_QNAME = new QName("equipamento.ws.oee.tc.feevale.br", "excluirEquipamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirEquipamentoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIREQUIPAMENTOSERVICE_WSDL_LOCATION = url;
        EXCLUIREQUIPAMENTOSERVICE_EXCEPTION = e;
    }

    public ExcluirEquipamentoService() {
        super(__getWsdlLocation(), EXCLUIREQUIPAMENTOSERVICE_QNAME);
    }

    public ExcluirEquipamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIREQUIPAMENTOSERVICE_QNAME, features);
    }

    public ExcluirEquipamentoService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIREQUIPAMENTOSERVICE_QNAME);
    }

    public ExcluirEquipamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIREQUIPAMENTOSERVICE_QNAME, features);
    }

    public ExcluirEquipamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirEquipamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirEquipamento
     */
    @WebEndpoint(name = "excluirEquipamentoSoap11")
    public ExcluirEquipamento getExcluirEquipamentoSoap11() {
        return super.getPort(new QName("equipamento.ws.oee.tc.feevale.br", "excluirEquipamentoSoap11"), ExcluirEquipamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirEquipamento
     */
    @WebEndpoint(name = "excluirEquipamentoSoap11")
    public ExcluirEquipamento getExcluirEquipamentoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("equipamento.ws.oee.tc.feevale.br", "excluirEquipamentoSoap11"), ExcluirEquipamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIREQUIPAMENTOSERVICE_EXCEPTION!= null) {
            throw EXCLUIREQUIPAMENTOSERVICE_EXCEPTION;
        }
        return EXCLUIREQUIPAMENTOSERVICE_WSDL_LOCATION;
    }

}
