
package br.feevale.tc.oee.ws.equipamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "excluirEquipamento", targetNamespace = "equipamento.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExcluirEquipamento {


    /**
     * 
     * @param excluirEquipamentoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.equipamento.ExcluirEquipamentoResponse
     */
    @WebMethod
    @WebResult(name = "excluirEquipamentoResponse", targetNamespace = "equipamento.ws.oee.tc.feevale.br", partName = "excluirEquipamentoResponse")
    public ExcluirEquipamentoResponse excluirEquipamento(
        @WebParam(name = "excluirEquipamentoRequest", targetNamespace = "equipamento.ws.oee.tc.feevale.br", partName = "excluirEquipamentoRequest")
        ExcluirEquipamentoRequest excluirEquipamentoRequest);

}
