
package br.feevale.tc.oee.ws.equipamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inserirOuAlterarEquipamentoService", targetNamespace = "equipamento.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/inserirOuAlterarEquipamentoServiceDefinition.wsdl")
public class InserirOuAlterarEquipamentoService
    extends Service
{

    private final static URL INSERIROUALTERAREQUIPAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERIROUALTERAREQUIPAMENTOSERVICE_EXCEPTION;
    private final static QName INSERIROUALTERAREQUIPAMENTOSERVICE_QNAME = new QName("equipamento.ws.oee.tc.feevale.br", "inserirOuAlterarEquipamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/inserirOuAlterarEquipamentoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERIROUALTERAREQUIPAMENTOSERVICE_WSDL_LOCATION = url;
        INSERIROUALTERAREQUIPAMENTOSERVICE_EXCEPTION = e;
    }

    public InserirOuAlterarEquipamentoService() {
        super(__getWsdlLocation(), INSERIROUALTERAREQUIPAMENTOSERVICE_QNAME);
    }

    public InserirOuAlterarEquipamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERIROUALTERAREQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirOuAlterarEquipamentoService(URL wsdlLocation) {
        super(wsdlLocation, INSERIROUALTERAREQUIPAMENTOSERVICE_QNAME);
    }

    public InserirOuAlterarEquipamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERIROUALTERAREQUIPAMENTOSERVICE_QNAME, features);
    }

    public InserirOuAlterarEquipamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserirOuAlterarEquipamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InserirOuAlterarEquipamento
     */
    @WebEndpoint(name = "inserirOuAlterarEquipamentoSoap11")
    public InserirOuAlterarEquipamento getInserirOuAlterarEquipamentoSoap11() {
        return super.getPort(new QName("equipamento.ws.oee.tc.feevale.br", "inserirOuAlterarEquipamentoSoap11"), InserirOuAlterarEquipamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InserirOuAlterarEquipamento
     */
    @WebEndpoint(name = "inserirOuAlterarEquipamentoSoap11")
    public InserirOuAlterarEquipamento getInserirOuAlterarEquipamentoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("equipamento.ws.oee.tc.feevale.br", "inserirOuAlterarEquipamentoSoap11"), InserirOuAlterarEquipamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERIROUALTERAREQUIPAMENTOSERVICE_EXCEPTION!= null) {
            throw INSERIROUALTERAREQUIPAMENTOSERVICE_EXCEPTION;
        }
        return INSERIROUALTERAREQUIPAMENTOSERVICE_WSDL_LOCATION;
    }

}
