
package br.feevale.tc.oee.ws.ordemproducao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "excluirOrdemProducaoService", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br", wsdlLocation = "http://localhost:8080/oee/ws/excluirOrdemProducaoServiceDefinition.wsdl")
public class ExcluirOrdemProducaoService
    extends Service
{

    private final static URL EXCLUIRORDEMPRODUCAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCLUIRORDEMPRODUCAOSERVICE_EXCEPTION;
    private final static QName EXCLUIRORDEMPRODUCAOSERVICE_QNAME = new QName("ordemProducao.ws.oee.tc.feevale.br", "excluirOrdemProducaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oee/ws/excluirOrdemProducaoServiceDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCLUIRORDEMPRODUCAOSERVICE_WSDL_LOCATION = url;
        EXCLUIRORDEMPRODUCAOSERVICE_EXCEPTION = e;
    }

    public ExcluirOrdemProducaoService() {
        super(__getWsdlLocation(), EXCLUIRORDEMPRODUCAOSERVICE_QNAME);
    }

    public ExcluirOrdemProducaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCLUIRORDEMPRODUCAOSERVICE_QNAME, features);
    }

    public ExcluirOrdemProducaoService(URL wsdlLocation) {
        super(wsdlLocation, EXCLUIRORDEMPRODUCAOSERVICE_QNAME);
    }

    public ExcluirOrdemProducaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCLUIRORDEMPRODUCAOSERVICE_QNAME, features);
    }

    public ExcluirOrdemProducaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcluirOrdemProducaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExcluirOrdemProducao
     */
    @WebEndpoint(name = "excluirOrdemProducaoSoap11")
    public ExcluirOrdemProducao getExcluirOrdemProducaoSoap11() {
        return super.getPort(new QName("ordemProducao.ws.oee.tc.feevale.br", "excluirOrdemProducaoSoap11"), ExcluirOrdemProducao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcluirOrdemProducao
     */
    @WebEndpoint(name = "excluirOrdemProducaoSoap11")
    public ExcluirOrdemProducao getExcluirOrdemProducaoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("ordemProducao.ws.oee.tc.feevale.br", "excluirOrdemProducaoSoap11"), ExcluirOrdemProducao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCLUIRORDEMPRODUCAOSERVICE_EXCEPTION!= null) {
            throw EXCLUIRORDEMPRODUCAOSERVICE_EXCEPTION;
        }
        return EXCLUIRORDEMPRODUCAOSERVICE_WSDL_LOCATION;
    }

}
