
package br.feevale.tc.oee.ws.ordemproducao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "excluirOrdemProducao", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExcluirOrdemProducao {


    /**
     * 
     * @param excluirOrdemProducaoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.ordemproducao.ExcluirOrdemProducaoResponse
     */
    @WebMethod
    @WebResult(name = "excluirOrdemProducaoResponse", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br", partName = "excluirOrdemProducaoResponse")
    public ExcluirOrdemProducaoResponse excluirOrdemProducao(
        @WebParam(name = "excluirOrdemProducaoRequest", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br", partName = "excluirOrdemProducaoRequest")
        ExcluirOrdemProducaoRequest excluirOrdemProducaoRequest);

}
