
package br.feevale.tc.oee.ws.ordemproducao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "inserirOuAlterarOrdemProducao", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InserirOuAlterarOrdemProducao {


    /**
     * 
     * @param inserirOuAlterarOrdemProducaoRequest
     * @return
     *     returns br.feevale.tc.oee.ws.ordemproducao.InserirOuAlterarOrdemProducaoResponse
     */
    @WebMethod
    @WebResult(name = "inserirOuAlterarOrdemProducaoResponse", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br", partName = "inserirOuAlterarOrdemProducaoResponse")
    public InserirOuAlterarOrdemProducaoResponse inserirOuAlterarOrdemProducao(
        @WebParam(name = "inserirOuAlterarOrdemProducaoRequest", targetNamespace = "ordemProducao.ws.oee.tc.feevale.br", partName = "inserirOuAlterarOrdemProducaoRequest")
        InserirOuAlterarOrdemProducaoRequest inserirOuAlterarOrdemProducaoRequest);

}
